### ISSUE TITLE
无法从指定集数开始修改文件名

### ISSUE THREAD

**Issue by Kunay0509** [jkoor/Alist-Media-Rename#12]
![image](https://github.com/user-attachments/assets/28283544-8f3e-408a-8d74-954f0a92c83d)
之前已经统一修改过已经保存过的文件名，现在将新更新的视频保存到网盘后想修改文件名发现读取不出来未修改的文件
![image](https://github.com/user-attachments/assets/0cbbfe9a-999f-4734-a220-0c1599537001)

**Comment by Kunay0509** [comment]
补充一下，如果不选择从指定集数开始的话可以读取到文件，但会从第一集识别修改
![image](https://github.com/user-attachments/assets/12a6838f-16e9-431e-9ad6-005b33cc8b19)

**Comment by jkoor** [comment]
我修复一下

**Comment by jkoor** [comment]
这种情况下，不应该指定从第几集开始命名，程序正常来说会自动排除已命名的文件，并按序号继续命名，也就是你补充的方案。我这边测试了一下，是可以排除已命名的文件，从1140集开始命名的。

用的是最新版吗？可以提供点详细信息，不过在测试的时候也发现了几个其他的bug

**Comment by jkoor** [comment]
> 补充一下，如果不选择从指定集数开始的话可以读取到文件，但会从第一集识别修改 ![image](https://private-user-images.githubusercontent.com/105988110/390660589-12a6838f-16e9-431e-9ad6-005b33cc8b19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODQwMTMsIm5iZiI6MTczMjc4MzcxMywicGF0aCI6Ii8xMDU5ODgxMTAvMzkwNjYwNTg5LTEyYTY4MzhmLTE2ZTktNDMxZS05YWQ2LTAwNWIzM2NjOGIxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwODQ4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTA4MzQ1NGQwYmM2MjA1MmU4MGE5ODVjYzAwYjBjNGZkZjVlYzc3NDgxZDM3ZTU2NGI5ZTI0ZTZmNzY4NGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G6O9lCQ_MYt7PKwohAsqTdcHNWLsjAfKKqCeXcgHpo0)

这种情况下，不应该指定从第几集开始命名，程序正常来说会自动排除已命名的文件，并按序号继续命名，也就是你补充的方案。我这边测试了一下，是可以排除已命名的文件，从1140集开始命名的。

用的是最新版吗？可以提供点详细信息，不过在测试的时候也发现了几个其他的bug

**Comment by Kunay0509** [comment]
> > 补充一下，如果不选择从指定集数开始的话可以读取到文件，但会从第一集识别修改 ![image](https://private-user-images.githubusercontent.com/105988110/390660589-12a6838f-16e9-431e-9ad6-005b33cc8b19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODQwMTMsIm5iZiI6MTczMjc4MzcxMywicGF0aCI6Ii8xMDU5ODgxMTAvMzkwNjYwNTg5LTEyYTY4MzhmLTE2ZTktNDMxZS05YWQ2LTAwNWIzM2NjOGIxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwODQ4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTA4MzQ1NGQwYmM2MjA1MmU4MGE5ODVjYzAwYjBjNGZkZjVlYzc3NDgxZDM3ZTU2NGI5ZTI0ZTZmNzY4NGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G6O9lCQ_MYt7PKwohAsqTdcHNWLsjAfKKqCeXcgHpo0)
> 
> 这种情况下，不应该指定从第几集开始命名，程序正常来说会自动排除已命名的文件，并按序号继续命名，也就是你补充的方案。我这边测试了一下，是可以排除已命名的文件，从1140集开始命名的。
> 
> 用的是最新版吗？可以提供点详细信息，不过在测试的时候也发现了几个其他的bug

用的2.4.0，刚才还更新到了2.5.1还是不行
我的推测是我没有保存全部的资源，只有1100集后面的视频，所以他找不到1-1100集的文件，就自动从第1集开始编码了？这个可以从指定集数开始吗？

**Comment by jkoor** [comment]
我个人的使用场景比较简单，基本都是全集保存，在添加了排除已重命名文件这个功能后，确实没用过`-n`这个参数了。

排除已重命名文件和`-n`这个参数在文件筛选逻辑上有点冲突，暂时还没想到一个合理的逻辑处理方式。

这种情况我的建议是先把未重命名的文件单独放在一个文件夹，然后使用`-n`参数应该就行了，重命名完后再合并。

此外，如果第一次重命名没有命名失败的文件的话，这两个功能应该也不会同时用到了。测试《柯南》的时候发现部分标题里有文件名禁止使用的非法字符，如`/`，这个现在我加了替换，文件重命名失败的问题应该会少很多。

**Comment by jkoor** [comment]
改了下程序，这次应该可以解决这个问题了，指定序号命名时，若存在已重命名的文件，会自动跳过。

**Comment by Kunay0509** [comment]
> 改了下程序，这次应该可以解决这个问题了，指定序号命名时，若存在已重命名的文件，会自动跳过。

刚才更新测试了一下，问题解决了，感谢修复~
