### ISSUE TITLE
config.json文件格式优化

### ISSUE THREAD

**Issue by vmlive** [jkoor/Alist-Media-Rename#17]
现在的config.json文件格式有点乱，修改不便。建议优化文件格式，如：每条功能一行，同时增加对每个字段的说明、解释，提高自定义重命名的可操作性。

**Comment by jkoor** [comment]
1. `.json`不支持注释，`.yaml`可读性强但需要额外安装一个库，所以之前出于最小化原则使用了`.json`。现在把模块打包了，不用自己挨个安装库了，`.yaml`似乎是更好一点了。

2. 至于结构方面，一开始是每个一行的，后面分了 3 部分，alist 配置一部分，tmdb 配置一部分，amr 程序配置一部分，感觉现在更加合理一点吧。

3. 现在使用方式还是不符合逻辑，考虑应该把程序本身打包成一个库,这样更新也更为容易，届时我会考虑支持`yaml`格式，可读性更强。正确使用逻辑应该是：
```bash
pip install amr
amr 刀剑神域 -d /刀剑神域
```
而不是
```bash
download main.py
pip install alistmediarename
python main.py 刀剑神域 -d /刀剑神域
```

**Comment by vmlive** [comment]
👍
