### ISSUE TITLE
希望更新1.7版本的main.exe

### ISSUE THREAD

**Issue by chenlu964** [jkoor/Alist-Media-Rename#2]
现在一次改完50个文件夹 还得看网盘的目录树查询失败的再改 感觉不够智能

**Comment by jkoor** [comment]
已添加 v1.7 的 exe 版，不过更推荐直接使用 Python 运行。

重命名失败的原因有很多，在我实际体验中绝大多数都是网络请求频繁的原因，这个无法解决，其他因素的话可以反馈。

**Comment by chenlu964** [comment]
好的
