### ISSUE TITLE
建议文件夹重命名规则对于有多季的剧集加上第x季/Season X的后缀

### ISSUE THREAD

**Issue by x6ufeng** [jkoor/Alist-Media-Rename#6]
避免在同一个大目录下不同季目录命名冲突的问题,避免连续命名导致覆盖的惨剧

**Comment by jkoor** [comment]
关于多季度文件夹命名一直没想到一个比较好的实现方式，我理想中的文件结构是这样的，但这涉及多层文件夹，处理较为麻烦。：
```
├─ 武林外传 (2006)
│  ├─ 1x01.mp4
│  └─ 1x02.mp4
├─ 刀剑神域 (2012)
│  ├─ Season 1
│     ├─ 1x01.mp4
│     └─ 1x02.mp4
│  └─ Season 2
│     ├─ 2x01.mp4
│     └─ 2x02.mp4
```
至于你提到的这种命名方式可以尝试修改配置文件`config.json`参数实现：
> 注意，之前的版本有bug，请同步到我最新发的v2.2版本

```
    "media_folder_rename": 2,
    "tv_season_format": "{name} ({year}) Season {season}",
```
命名结果举例：`刀剑神域 (2012) Season 1`
其中的`{name}`, `{year}`, `{season}`均为变量，会自动替换，也可以仅使用其中任意的变量，你可以自由设置。
