### ISSUE TITLE
输入季数后识别出错

### ISSUE THREAD

**Issue by x6ufeng** [jkoor/Alist-Media-Rename#9]
![IMAGE 2024-09-30 21:17:41](https://github.com/user-attachments/assets/fd8a38a1-2a8a-4330-ad7c-4c63b3c198ef)
![IMAGE 2024-09-30 21:17:43](https://github.com/user-attachments/assets/eeb40cf4-564b-470b-b435-52f11cc3541e)
系统macOS15
python版本3.12

**Comment by jkoor** [comment]
这块序号应该是从0开始，有空我改一下

**Comment by jkoor** [comment]
这个 bug 已经修复了，可以试试
